"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.specialities": "Specialities",
    "nav.coe": "Centre Of Excellence",
    "nav.career": "Career",
    "nav.patient": "Patient",
    "nav.news": "News",
    "nav.diagnostic": "Diagnostics",
    "nav.diagnostic.habit": "Browse by Habit",
    "nav.diagnostic.packages": "Packages",
    "nav.diagnostic.risk": "Browse by Risk",
    "nav.diag.risk.acidity": "Acidity",
    "nav.diag.risk.allergy": "Allergy",
    "nav.diag.risk.anaemia": "Anaemia",
    "nav.diag.risk.arthritis": "Arthritis",
    "nav.diag.risk.cancer": "Cancer",
    "nav.diag.risk.diabetes": "Diabetes",
    "nav.diag.risk.digestion": "Digestion",
    "nav.diag.risk.fever": "Fever",
    "nav.diag.risk.heart": "Heart",
    "nav.diag.risk.hepatitis": "Hepatitis",
    "nav.diag.risk.hormones": "Hormones",
    "nav.diag.risk.hypertension": "Hypertension",
    "nav.diag.risk.immunity": "Immunity",
    "nav.diag.risk.infection": "Infection",
    "nav.diag.risk.jaundice": "Jaundice",
    "nav.diag.risk.joints": "Joints",
    "nav.diag.risk.kidney": "Kidney",
    "nav.diag.risk.liver": "Liver",
    "nav.diag.risk.obesity": "Obesity",
    "nav.diag.risk.pregnancy": "Pregnancy",
    "nav.diag.risk.std": "STD",
    "nav.diag.risk.thyroid": "Thyroid",
    "nav.diag.risk.inflammation": "Inflammation",
    "nav.diag.risk.vitamins": "Vitamins",
    "nav.diag.habit.alcoholism": "Alcoholism",
    "nav.diag.habit.anger": "Anger",
    "nav.diag.habit.heartburn": "Heartburn",
    "nav.diag.habit.junk-food": "Junk Food",
    "nav.diag.habit.low-iron": "Low Iron Diet",
    "nav.diag.habit.appetite": "Loss of Appetite",
    "nav.diag.habit.nutrition": "Poor Nutrition",
    "nav.diag.habit.sleeplessness": "Sleeplessness",
    "nav.diag.habit.smoking": "Smoking",
    "nav.diag.habit.stress": "Stress",
    "nav.diag.habit.tiredness": "Tiredness",
    "nav.diag.habit.allergy": "Allergy",
    "nav.diag.habit.arthritis": "Arthritis",
    "nav.diag.habit.diabetes": "Diabetes",
    "nav.diag.habit.fever": "Fever",
    "nav.diag.habit.hepatitis": "Hepatitis",
    "nav.diag.habit.hypertension": "Hypertension",
    "nav.diag.habit.infection": "Infection",
    "nav.diag.habit.joints": "Joints",
    "nav.diag.habit.liver": "Liver",
    "nav.diag.habit.pregnancy": "Pregnancy",
    "nav.diag.habit.thyroid": "Thyroid",
    "nav.diag.habit.vitamins": "Vitamins",
    "nav.diag.pkg.silver": "Silver Full Body Checkup",
    "nav.diag.pkg.gold": "Gold Full Body Checkup",
    "nav.diag.pkg.platinum": "Platinum Full Body Checkup",
    "nav.diag.pkg.cardiac": "Cardiac Screening",
    "nav.diag.pkg.senior": "Senior Citizen Package",
    "nav.diag.pkg.woman": "Well Woman Package",
    "nav.diag.pkg.influenza": "Influenza Virus Panel",
    "nav.diag.pkg.diamond": "Diamond Full Body Checkup",
    "nav.diag.pkg.mbg": "MBG Health Panel",
    "nav.diag.pkg.anemia": "Anemia Profile (Comprehensive)",
    "nav.diag.pkg.cancer": "Cancer Screening Panel",
    "nav.diag.pkg.health1": "Health Screen Test 1",
    "diag.detail.availablePackages": "Available Packages for",
    "diag.detail.viewPackage": "View Package",
    "diag.detail.off": "OFF",
    "diag.list.riskTitle": "Comprehensive Risk Categories",
    "diag.list.riskSubtitle": "Browse diagnostic tests by clinical risk factors to find the most accurate health assessment.",
    "diag.list.habitTitle": "Comprehensive Habit Categories",
    "diag.list.habitSubtitle": "Find relevant diagnostic checks based on lifestyle patterns and routine habits.",
    "diag.list.explore": "Explore Tests",
    "page.spec.list.title": "Our Specialities",
    "page.spec.list.subtitle": "World-class medical expertise across all major clinical departments.",
    "page.spec.list.badge": "Center of Excellence",
    "page.spec.list.back": "Back to Specialities",
    "page.spec.list.viewDetail": "View Details",
    "nav.findDoctor": "Find a Doctor",
    "nav.contact": "Contact Us",
    "nav.bookAppointment": "Book Now",
    "header.emergency": "Reception: 011-40793535, 8588831732",
    "page.doctor.experience": "Total Experience",
    "page.doctor.education": "Education & Qualifications",
    "page.doctor.interests": "Areas of Interest",
    "page.doctor.associations": "Hospitals Associated With",
    "page.doctor.years": "Years",
    "page.doctor.awards": "Awards & Recognition",
    "page.doctor.consult": "Consult with",
    // About dropdown
    "nav.about.overview": "About Overview",
    "nav.about.corporate": "Our Corporate Profile",
    "nav.about.director": "Message from Chairman",
    "nav.about.vision": "Vision & Mission",
    "nav.about.management": "Management Team",
    "nav.about.services247": "24x7 Services",
    "nav.about.accreditation": "Accreditations",
    // Specialities
    "nav.spec.medicine": "Internal Medicine",
    "nav.spec.obst": "Obstetrics & Gynaecology",
    "nav.spec.endo": "Endocrinology",
    "nav.spec.infectious": "Infectious Disease",
    "nav.spec.surgery": "Surgery",
    "nav.spec.ortho": "Orthopaedics",
    "nav.spec.cardiology": "Cardiology",
    "nav.spec.neuro": "Neurology",
    "nav.spec.paediatrics": "Paediatrics",
    "nav.spec.urology": "Urology",
    "nav.spec.gastro": "Gastroenterology",
    "nav.spec.psychiatry": "Psychiatry",
    "nav.spec.dentistry": "Dentistry",
    "nav.spec.radiology": "Radiology",
    "nav.spec.pathology": "Pathology",
    "nav.spec.ophthalmology": "Ophthalmology",
    "nav.spec.maxillofacial": "Oral Maxillofacial Surgery",
    // COE dropdown
    "nav.coe.maternity": "Maternity Centre",
    "nav.coe.laparoscopic": "Laparoscopic & General Surgery",
    "nav.coe.pediatrics": "Pediatrics & Neonatology",
    "nav.coe.interventional": "Interventional Radiology",
    "nav.coe.nephrology": "Nephrology",
    "nav.coe.urology": "Urology & Andrology",
    "nav.coe.ortho": "Joint Replacement Centre",
    "nav.coe.bariatric": "Bariatric Surgery Centre",
    "nav.coe.cancer": "Cancer Care Centre",
    "nav.coe.emergency": "Emergency & Trauma",
    "nav.coe.icu": "Critical Care & ICU",
    // Patient dropdown
    "nav.patient.rights": "Patient Rights",
    "nav.patient.feedback": "Feedback",
    "nav.patient.insurance": "Insurance Assistance",
    "nav.patient.visiting": "Visiting Hours",
    // Hero
    "hero.tagline": "Aiming health through Love & Care",
    "hero.subtitle":
      "A Multi Speciality Hospital in East Delhi serving since 2011 with clinical excellence and compassion.",
    "hero.cta.book": "Book an Appointment",
    "hero.cta.specialities": "Our Specialities",
    "hero.badge": "NABH Accredited Hospital",
    // Stats
    "stats.years": "Years of Excellence",
    "stats.doctors": "Expert Doctors",
    "stats.patients": "Happy Patients",
    "stats.specialities": "Specialities",
    // Services
    "services.title": "Our Specialities",
    "services.subtitle":
      "Experienced doctors with expertise across specialities providing complete care.",
    "services.viewmore": "View All Specialities",
    // Spec descriptions
    "spec.medicine.desc": "Preventive care, diagnosis, and treatment for adult diseases.",
    "spec.obst.desc": "Complete maternal care through pregnancy, delivery, and all gynaecological conditions.",
    "spec.obst.t1": "Maternity & High-Risk Pregnancy",
    "spec.obst.t2": "Laparoscopic Gynaecology Surgeries",
    "spec.obst.t3": "Infertility & IVF Clinics",
    "spec.endo.desc": "Expert care in diabetes, thyroid, and other endocrine system disorders.",
    "spec.endo.t1": "Diabetes & Thyroid Management",
    "spec.endo.t2": "Obesity & Weight Management",
    "spec.endo.t3": "Hormonal Disorders",
    "spec.infectious.desc": "Comprehensive diagnosis and treatment for various infections and communicable diseases.",
    "spec.infectious.t1": "Fever & Unknown Origins",
    "spec.infectious.t2": "Immunization & Vaccination",
    "spec.infectious.t3": "Travel Medicine",
    "spec.surgery.desc": "From cancer surgeries to bariatric in our modular operation theatres.",
    "spec.surgery.t1": "Minimal Access Surgeries",
    "spec.surgery.t2": "Bariatric & Weight Loss Surgery",
    "spec.surgery.t3": "Onco-Surgery",
    "spec.ortho.desc": "Expert care for bone & joint problems, fractures, and arthritis.",
    "spec.ortho.t1": "Knee & Hip Replacement",
    "spec.ortho.t2": "Arthroscopy & Sports Injuries",
    "spec.ortho.t3": "Complex Trauma & Fracture Care",
    "spec.cardiology.desc": "Advanced cardiac care, emergency response, and post-surgery rehabilitation.",
    "spec.cardiology.t1": "Coronary Angiography",
    "spec.cardiology.t2": "Echocardiography (ECG, TMT, Holter)",
    "spec.cardiology.t3": "Heart Failure Clinic",
    "spec.neuro.desc": "Diagnosis and management of complex neurological and brain conditions.",
    "spec.neuro.t1": "Stroke & Paralysis Management",
    "spec.neuro.t2": "Headache & Migraine Therapy",
    "spec.neuro.t3": "Epilepsy Clinics",
    "spec.paediatrics.desc": "Round-the-clock pediatric emergency, NICU, and child care.",
    "spec.paediatrics.t1": "Neonatal Intensive Care (NICU)",
    "spec.paediatrics.t2": "Paediatric Immunization",
    "spec.paediatrics.t3": "Child Development Clinics",
    "spec.urology.desc": "Treatment of urinary tract diseases and male reproductive system conditions.",
    "spec.urology.t1": "Kidney Stone Laser Removal",
    "spec.urology.t2": "Prostate Surgeries (TURP)",
    "spec.urology.t3": "Uro-Oncology",
    // Why choose us
    "why.title": "Why Choose Karuna Hospital?",
    "why.clinical.title": "Clinical Excellence",
    "why.clinical.desc":
      "Collective clinical experience of over 200 years across specialities.",
    "why.lab.title": "State-Of-The-Art Laboratory",
    "why.lab.desc":
      "End-to-end diagnostic services in partnership with Oncquest Laboratories.",
    "why.emergency.title": "24/7 Emergency Services",
    "why.emergency.desc":
      "Rapid response in trauma and casualty cases with quick ambulance services.",
    "why.pharmacy.title": "In-House Pharmacy",
    "why.pharmacy.desc":
      "Access quality medicines ensuring complete treatment at every stage.",
    // Director
    "director.title": "Director's Message",
    "director.name": "Dr. (Director)",
    "director.quote":
      '"Karuna" reflects in our clear communication, making the patients feel at home, and the understanding with which we approach treatment.',
    "director.readmore": "Read More",
    // CTA
    "cta.title": "Start Your Journey To Improved Health Today",
    "cta.subtitle":
      "Our team of expert doctors is ready to provide you with the best care.",
    "cta.button": "Book An Appointment",
    // Footer
    "footer.tagline": "Aiming health through Love & Care",
    "footer.address":
      "D-62, Pocket E, Dilshad Colony, New Delhi, Delhi, 110095",
    // Inner Pages Common
    "page.back_home": "Back to Home",
    "page.error.title": "Information Not Found",
    // COE
    "page.coe.notfound": "The centre of excellence you are looking for does not exist or has been moved.",
    "page.coe.badge": "Centre Of Excellence",
    "page.coe.welcome": "Welcome to",
    "page.coe.desc": "We are dedicated to providing world-class care. Our expert team utilizes the latest evidence-based protocols and state-of-the-art facilities to deliver comprehensive and compassionate treatments. At Karuna Hospital, our focus is always on patient-centric care to ensure the best possible medical outcomes.",
    "page.coe.expert": "Expert Care",
    "page.coe.expert.desc": "Highly qualified specialists with years of clinical experience in their respective fields.",
    "page.coe.advanced": "Advanced Facilities",
    "page.coe.advanced.desc": "State-of-the-art medical equipment and modern infrastructure prioritizing your health.",
    "page.cta.healing": "Start Your Healing Journey Today",
    "page.cta.healing.desc": "Book a consultation with our highly experienced specialists.",
    // Speciality
    "page.spec.notfound": "The speciality department you are looking for does not exist or has been moved.",
    "page.spec.badge": "Speciality Department",
    "page.spec.welcome": "Welcome to",
    "page.spec.desc": "Our expert medical team is deeply committed to diagnosing and treating related conditions. Equipped with the latest in modern medical technology and following leading evidence-based practices, we offer a comprehensive approach dedicated entirely to your health and recovery journey.",
    "page.spec.expert": "Specialized Experts",
    "page.spec.expert.desc": "Our team comprises of some of the leading doctors specializing in diagnosing complex conditions.",
    "page.spec.patient": "Patient-First Care",
    "page.spec.patient.desc": "A highly personalized care model focusing on comfort, transparency, and superior outcomes.",
    "page.spec.treatments": "Key Treatments & Services",
    "page.cta.consult": "Schedule a Consultation",
    "page.cta.consult.desc": "Speak with our expert consultants today about your health concerns.",
    // Patient
    "page.patient.badge": "Patient Information",
    "page.patient.rights.desc": "Every patient has the right to considerate and respectful care. At Karuna Hospital, we are dedicated to ensuring you feel informed, secure, and empowered throughout your healthcare journey. Our policies are designed to respect personal dignity and maintain the utmost confidentiality.",
    "page.patient.feedback.desc": "Your feedback is invaluable to us. We constantly strive to improve our services and patient experiences. Whether you have a compliment for our staff or a suggestion for how we can do better, we want to hear from you.",
    "page.patient.insurance.desc": "We understand that navigating healthcare finances can be challenging. Karuna Hospital is empaneled with major health insurance providers and TPAs to offer cashless hospitalization facilities. Our dedicated insurance desk is here to assist you with pre-authorization and claims.",
    "page.patient.visiting.desc": "To ensure our patients get the rest they need while staying connected with their loved ones, we have established specific visiting hours. In general wards, visiting is permitted twice daily. In ICUs, visiting is restricted to ensure a sterile and calm environment for critical patients.",
    // About
    "page.about.title": "Who We Are",
    "page.about.subtitle": "Excellence and empathy in healthcare for the local community.",
    "page.about.heroSubtitle": "A premier multi-speciality hospital in East Delhi dedicated to clinical excellence and compassionate care since 2011.",
    "page.about.overview": "About Karuna Hospital",
    "page.about.p1": "Established in 2011, Karuna Hospital was founded with a singular purpose: to bridge the gap in healthcare needs for those who truly need it. Over the years, we have grown into a trusted multi-speciality healthcare facility in East Delhi, known for combining clinical excellence with a deeply empathetic approach.",
    "page.about.p2": "Our dedicated team of experienced doctors and medical professionals leverage advanced technology to provide high-quality, affordable healthcare.",
    "page.about.corporate.title": "Our Corporate Profile",
    "page.about.chairman.title": "Message from Chairman",
    "page.about.management.title": "Management Team",
    "page.about.services247.title": "24x7 Services",
    "page.about.vision.title": "Our Vision",
    "page.about.vision.desc": "Karuna Hospital seeks excellence in all it’s endeavours, aspiring to provide state of the art medical services to all strata of society at affordable prices, establishing and enduring doctor-patient relationships, and to nurture and environment where healthcare providers and staff can learn and thrive.",
    "page.about.mission.title": "Our Mission",
    "page.about.mission.desc": "Karuna means empathy, Our name symbolizes our mission in its entirety. Providing outstanding healthcare facilities to all with compassion and respect, and promoting wellness and good health in the community through preventive education and services embedded with love and care.",
    "page.about.values.title": "Quality Values and initiatives",
    "page.about.values.1": "To provide exceptional care to patients and their families.",
    "page.about.values.2": "To acknowledge the dignity and individuality of every patient and staff member.",
    "page.about.values.3": "To respect patient’s privacy and confidentially.",
    "page.about.values.4": "To communicate openly and effectively with patients and staff.",
    "page.about.values.5": "To maintain the highest standards of integrity and ethical conduct.",
    "page.about.values.6": "To foster teamwork and accountability at all levels.",
    "page.about.values.7": "To promote ongoing evaluation and performance improvement.",
    "page.about.values.8": "To build upon efficient and prudent management practices to ensure financial well being and responsibility.",
    "page.about.awards.title": "Awards & Accreditations",
    "page.about.awards.desc": "We are proud to be recognized by leading health and quality regulators in the country. This ensures that every test, procedure, and surgery meets global safety and quality standards.",
    // Career
    "page.career.title": "Join Our Team",
    "page.career.subtitle": "Build a rewarding career focusing on empathy and clinical excellence.",
    "page.career.why": "Why Work With Us?",
    "page.career.why.desc": "At Karuna Hospital, our employees are our greatest asset. We foster a collaborative, inclusive, and modern work environment where highly trained professionals are encouraged to thrive, innovate, and make an active difference in our patients' lives.",
    "page.career.growth": "Growth Opportunities",
    "page.career.growth.desc": "We prioritize continuous learning and professional development through rigorous training and mentoring.",
    "page.career.collab": "Collaborative Culture",
    "page.career.collab.desc": "Work in multidisciplinary teams where your input is valued, ensuring holistic patient care.",
    "page.career.openings": "Current Openings",
    "page.career.apply": "Apply Now",
    "page.career.cantfind": "Can't find a matching role?",
    "page.career.sendresume": "Send your resume to our HR department and we'll reach out when a suitable position opens.",
    "page.career.contacthr": "Contact HR Department →",
    // Contact
    "page.contact.title": "Contact Us",
    "page.contact.subtitle": "Get in touch with us for appointments, inquiries, or feedback.",
    "page.contact.info": "Contact Information",
    "page.contact.address.label": "Address",
    "page.contact.phone.label": "Phone",
    "page.contact.email.label": "Email",
    "page.contact.hero.title": "Contact Us",
    "page.contact.hero.subtitle": "Reach out for appointments, emergencies, or general inquiries. Our care team is here to assist you 24/7. We look forward to hearing from you!",
    "page.contact.getInTouch": "Get in Touch",
    "page.contact.getInTouch.desc": "We are here to assist you 24/7. Reach out for appointments, emergencies, or general inquiries.",
    "page.contact.card.location": "Our Location",
    "page.contact.card.address": "D-62, Pocket E, Dilshad Colony, New Delhi, Delhi, 110095",
    "page.contact.card.call": "Call Us",
    "page.contact.card.email": "Email",
    "page.contact.card.emergency": "Emergency",
    "page.contact.card.emergency.desc": "24/7 Available — Call anytime",
    "page.contact.form.title": "Send Us a Message",
    "page.contact.form.subtitle": "Fill out the form below or message us directly on WhatsApp. Our care team will respond shortly.",
    "page.contact.form.name.label": "Full Name",
    "page.contact.form.email.label": "Email Address",
    "page.contact.form.phone.label": "Phone Number",
    "page.contact.form.subject.label": "Subject",
    "page.contact.form.message.label": "Your Message",
    "page.contact.form.privacy": "Your information is secure. We only use it to respond to your inquiry.",
    "page.contact.form.privacy.link": "Privacy Policy",
    "page.contact.form.sending": "Sending...",
    "page.contact.form.sent": "Message Sent!",
    "page.contact.form.send.btn": "Send Message via Form",
    "page.contact.form.or": "or",
    "page.contact.form.whatsapp": "Chat on WhatsApp",
    "page.contact.form.emergency.notice": "For medical emergencies, call our reception immediately.",
    "page.contact.form.subject.appointment": "Book an Appointment",
    "page.contact.form.subject.inquiry": "General Inquiry",
    "page.contact.form.subject.feedback": "Feedback",
    "page.contact.form.subject.emergency": "Emergency Assistance",
    "page.contact.form.subject.other": "Other",
    // News
    "page.news.title": "Latest Updates",
    "page.news.readfull": "Read Full Article",
    "footer.quicklinks": "Quick Links",
    "footer.contact": "Contact Us",
    "footer.rights": "© 2024 Karuna Hospital. All rights reserved.",
    "footer.nabh": "NABH Accredited",
    "home.about.badge": "About Us",
    "home.about.welcome": "Welcome to",
    "home.about.p1.title": "Established in 2011, Karuna Hospital is a leading multi-speciality healthcare facility in Delhi. We are committed to providing comprehensive, world-class medical services.",
    "home.about.p2.desc": "Empathy lies at the core of our ethos. Our team of experienced doctors and compassionate staff work tirelessly to deliver personalized care with the help of state-of-the-art infrastructure and highly accessible healthcare packages.",
    "home.about.discover": "Discover More",
    "home.infra.title": "Infrastructure & Technology",
    "home.infra.subtitle": "State-of-the-art facilities designed for patient comfort, safety, and advanced clinical care.",
    "home.infra.facility.title": "Our Facility",
    "home.infra.facility.desc": "A multi-speciality healthcare landmark in East Delhi, dedicated to providing world-class medical services since 2011.",
    "home.infra.lobby.title": "Premium Lobby",
    "home.infra.lobby.desc": "Patient-friendly environment with modern amenities.",
    "home.infra.care.title": "Compassionate Care",
    "home.infra.care.desc": "Expert doctors delivering personalized attention.",
    "home.infra.ot.title": "Modular OTs",
    "home.infra.ot.desc": "Equipped with ultra-modern surgical and diagnostic technology.",
    "home.director.p1": "As the name of the hospital suggests, Karuna Hospital was established to address the gap in the healthcare needs of people who truly need it.",
    "home.director.cite": "Director, Karuna Hospital",
    "page.about.chairman.label": "Message from Chairman",
    "page.about.director.title": "Director’s Message",
    "page.about.chairman.p1": "As the name of the hospital suggests, Karuna Hospital was established to address the gap in the healthcare needs of people who truly need it. Our processes, onboarding of doctors, treatment and state-of-the-art infrastructure have all been designed to bridge this gap.",
    "page.about.chairman.p2": "In my 35 years of medical practice, I have witnessed the wonders that the combination of medical knowledge and compassion can achieve.",
    "page.about.chairman.p3": "“Karuna” reflects in our clear communication, making the patients feel at home, and the understanding with which we approach treatment. This is what we try to inculcate in the behaviour of our staff, working culture and the perception of professionalism, while providing services to thousands of patients round-the-clock. Trust of our patients empowers us to march ahead and ensure healthcare for all.",
    "page.about.chairman.name": "Dr. Rajeev Gupta",
    "page.about.chairman.desig": "Chairman & Director",
    "page.about.mgmt.title": "Board of Directors",
    "page.about.mgmt.desc": "Dedicated professional contributing to the growth and excellence of Karuna Hospital.",
    "page.about.service.emergency": "Emergency & Trauma",
    "page.about.service.emergency.desc": "Round-the-clock emergency response with expert trauma teams.",
    "page.about.service.lab": "Diagnostic Lab",
    "page.about.service.lab.desc": "24/7 high-end diagnostic testing and imaging services.",
    "page.about.service.pharmacy": "Pharmacy",
    "page.about.service.pharmacy.desc": "Continuous access to quality healthcare medicines and supplies.",
    "page.about.service.ambulance": "Ambulance",
    "page.about.service.ambulance.desc": "Immediate ambulance pick-up and transport available 24/7.",
    "page.about.values.long": "At Karuna Hospital, excellence drives everything we do. We provide cutting-edge, affordable healthcare to all communities, build lasting doctor-patient partnerships, and nurture a supportive workplace where our staff can grow and excel. Backed by the finest healthcare team in the region, we deliver exceptional care with integrity and compassion.",
    "page.about.mission.heading": "Polished Mission Statement",
    "page.about.mission.long": "Karuna Hospital is committed to excellence in all we do. We strive to deliver state-of-the-art medical care to every segment of society at affordable prices, foster enduring doctor-patient relationships, and cultivate an environment where healthcare professionals and staff can continuously learn and thrive. Powered by an exceptional team, we are dedicated to setting the standard in compassionate, high-quality healthcare.",
    "page.diag.hero.badge": "State-of-the-Art Diagnostics",
    "page.diag.hero.title": "Precision Diagnosis, Personalized Care.",
    "page.diag.hero.subtitle": "Karuna Hospital partners with leading laboratories to provide end-to-end clinical assessments. Choose the right path for your health screening below.",
    "page.diag.hero.accuracy": "99.9% Accuracy",
    "page.diag.hero.processing": "24/7 Processing",
    "page.diag.hero.reports": "Digital Reports",
    "page.diag.cat.habit.title": "Browse by Habit",
    "page.diag.cat.habit.desc": "Lifestyle-based screenings for smoking, stress, and routine patterns.",
    "page.diag.cat.habit.stats": "20+ Habit Checks",
    "page.diag.cat.risk.title": "Browse by Risk",
    "page.diag.cat.risk.desc": "Targeted diagnostics for specific clinical risks like Diabetes or Heart disease.",
    "page.diag.cat.risk.stats": "30+ Risk Profiles",
    "page.diag.cat.package.title": "Health Packages",
    "page.diag.cat.package.desc": "Comprehensive full-body checkups curated for all age groups and needs.",
    "page.diag.cat.package.stats": "15+ Bundled Plans",
    "page.diag.trust.title": "Why our Clinical Assessments stand out.",
    "page.diag.trust.global.title": "Global Standards",
    "page.diag.trust.global.desc": "Our clinical diagnostic protocols are aligned with NABH and ISO benchmarks for total safety.",
    "page.diag.trust.expert.title": "Expert Interpretation",
    "page.diag.trust.expert.desc": "Every report is reviewed by specialized pathologists and MD physicians before release.",
    "page.diag.trust.stat.tat": "TAT for Routine",
    "page.diag.trust.stat.available": "Tests Available",
    "page.diag.trust.stat.lab": "Lab Availability",
    "page.diag.trust.stat.patient": "Patient First",
    "page.diag.help.title": "Need Assistance?",
    "page.diag.help.subtitle": "Need help choosing the right test? Our expert clinical team is available for guidance.",
    "page.diag.help.cta": "Speak with a Specialist",
    "page.doctors.badge": "Find Your Doctor",
    "page.doctors.title": "Our Expert Medical Team",
    "page.doctors.hero.p1": "Established in 2011, Karuna Hospital is known for its expertise in both outpatient and inpatient services. Empathy lies at the core of our services which reflects in compassionate treatment of our expert doctors and accessible cost structure.",
    "page.doctors.hero.p2": "Experienced doctors with expertise across specialities are associated with Karuna Hospital. This helps us in understanding our patients’ problems better and provide complete care.",
    "page.doctors.card.experience": "years experience",
    "page.doctors.card.viewProfile": "View Profile",
    "page.doctors.card.location": "Dilshad Colony, New Delhi",
    "page.news.badge": "Latest Updates",
    "page.news.hero.subtitle": "Stay up to date with the latest clinical breakthroughs, community service initiatives, and hospital announcements from Karuna Hospital.",
    "page.news.featured": "Featured",
    "page.news.milestone": "Milestone",
    "page.news.community": "Community",
    "page.news.expansion": "Expansion",
    "page.news.innovation": "Innovation",
    "page.news.award": "Award",
    "page.news.hospital": "Hospital News",
    "page.news.readTime": "Min Read",
    "page.doctor.verified": "Verified Expert",
    "page.doctor.patients": "Patients",
    "page.doctor.rating": "Rating",
    "page.doctor.tagline": "Senior specialist at Karuna Hospital, Dilshad Colony, New Delhi — dedicated to providing compassionate, evidence-based medical care.",
    "page.doctor.about": "About",
    "page.doctor.book": "Book a Consultation",
    "page.doctor.availability": "Availability",
    "page.doctor.mon_sat": "Mon – Sat, 9 AM – 6 PM",
    "page.doctor.location": "Karuna Hospital, Dilshad Colony, New Delhi",
    "page.doctor.why": "Why Karuna Hospital?",
    "page.doctor.needexpert": "Need Expert Medical Advice?",
    "page.doctor.schedule": "Schedule your appointment today for personalised, world-class care.",
    "page.career.badge": "Join Our Mission",
    "page.career.joinus": "Work With Us",
    "page.career.quote": "A place where medical excellence meets compassionate care at Karuna Hospital.",
    "page.career.progrowth": "Professional Growth",
    "page.career.progrowth.desc": "Continuous learning and development opportunities to advance your medical career at Karuna Hospital.",
    "page.career.collab.env": "Collaborative Environment",
    "page.career.collab.env.desc": "Work alongside some of the best medical professionals in a supportive, team-oriented culture.",
    "page.career.excellence": "Excellence & Recognition",
    "page.career.excellence.desc": "We value and reward outstanding patient care, dedication, and clinical excellence.",
    "page.career.tech": "Advanced Technology",
    "page.career.tech.desc": "Access to state-of-the-art medical equipment and innovative healthcare solutions.",
    "page.career.openings.p": "Join our team of specialists and support staff dedicated to providing the best healthcare services.",
  },
  hi: {
    // Header
    "nav.home": "होम",
    "nav.about": "हमारे बारे में",
    "nav.specialities": "विशेषताएं",
    "nav.coe": "उत्कृष्टता केंद्र",
    "nav.career": "करियर",
    "nav.patient": "मरीज़",
    "nav.news": "समाचार",
    "nav.diagnostic": "जांच",
    "nav.diagnostic.habit": "आदत के अनुसार खोजें",
    "nav.diagnostic.packages": "पैकेज",
    "nav.diagnostic.risk": "जोखिम के अनुसार खोजें",
    "nav.diag.risk.acidity": "एसिडिटी",
    "nav.diag.risk.allergy": "एलर्जी",
    "nav.diag.risk.anaemia": "एनीमिया",
    "nav.diag.risk.arthritis": "गठिया",
    "nav.diag.risk.cancer": "कैंसर",
    "nav.diag.risk.diabetes": "मधुमेह",
    "nav.diag.risk.digestion": "पाचन",
    "nav.diag.risk.fever": "बुखार",
    "nav.diag.risk.heart": "हृदय",
    "nav.diag.risk.hepatitis": "हेपेटाइटिस",
    "nav.diag.risk.hormones": "हार्मोन",
    "nav.diag.risk.hypertension": "उच्च रक्तचाप",
    "nav.diag.risk.immunity": "रोग प्रतिरोधक क्षमता",
    "nav.diag.risk.infection": "संक्रमण",
    "nav.diag.risk.jaundice": "पीलिया",
    "nav.diag.risk.joints": "जोड़",
    "nav.diag.risk.kidney": "किडनी",
    "nav.diag.risk.liver": "लिवर",
    "nav.diag.risk.obesity": "मोटापा",
    "nav.diag.risk.pregnancy": "गर्भावस्था",
    "nav.diag.risk.std": "एसटीडी",
    "nav.diag.risk.thyroid": "थायराइड",
    "nav.diag.risk.inflammation": "सूजन",
    "nav.diag.risk.vitamins": "विटामिन",
    "nav.diag.habit.alcoholism": "शराब की लत",
    "nav.diag.habit.anger": "क्रोध",
    "nav.diag.habit.heartburn": "सीने में जलन",
    "nav.diag.habit.junk-food": "जंक फूड",
    "nav.diag.habit.low-iron": "कम आयरन वाला आहार",
    "nav.diag.habit.appetite": "भूख न लगना",
    "nav.diag.habit.nutrition": "खराब पोषण",
    "nav.diag.habit.sleeplessness": "अनिद्रा",
    "nav.diag.habit.smoking": "धूम्रपान",
    "nav.diag.habit.stress": "तनाव",
    "nav.diag.habit.tiredness": "थकान",
    "nav.diag.habit.allergy": "एलर्जी",
    "nav.diag.habit.arthritis": "गठिया",
    "nav.diag.habit.diabetes": "मधुमेह",
    "nav.diag.habit.fever": "बुखार",
    "nav.diag.habit.hepatitis": "हेपेटाइटिस",
    "nav.diag.habit.hypertension": "उच्च रक्तचाप",
    "nav.diag.habit.infection": "संक्रमण",
    "nav.diag.habit.joints": "जोड़",
    "nav.diag.habit.liver": "लिवर",
    "nav.diag.habit.pregnancy": "गर्भावस्था",
    "nav.diag.habit.thyroid": "थायराइड",
    "nav.diag.habit.vitamins": "विटामिन",
    "nav.diag.pkg.silver": "सिल्वर फुल बॉडी चेकअप",
    "nav.diag.pkg.gold": "गोल्ड फुल बॉडी चेकअप",
    "nav.diag.pkg.platinum": "प्लेटिनम फुल बॉडी चेकअप",
    "nav.diag.pkg.cardiac": "कार्डिएक स्क्रीनिंग",
    "nav.diag.pkg.senior": "वरिष्ठ नागरिक पैकेज",
    "nav.diag.pkg.woman": "वेल वुमन पैकेज",
    "nav.diag.pkg.influenza": "इन्फ्लुएंजा वायरस पैनल",
    "nav.diag.pkg.diamond": "डायमंड फुल बॉडी चेकअप",
    "nav.diag.pkg.mbg": "एमबीजी स्वास्थ्य पैनल",
    "nav.diag.pkg.anemia": "एनीमिया प्रोफाइल (व्यापक)",
    "nav.diag.pkg.cancer": "कैंसर स्क्रीनिंग पैनल",
    "nav.diag.pkg.health1": "हेल्थ स्क्रीन टेस्ट 1",
    "page.doctor.awards": "पुरस्कार और मान्यता",
    "page.doctor.consult": "परामर्श करें",
    "diag.detail.availablePackages": "उपलब्ध पैकेज",
    "diag.detail.viewPackage": "पैकेज देखें",
    "diag.detail.off": "छूट",
    "diag.list.riskTitle": "व्यापक जोखिम श्रेणियां",
    "diag.list.riskSubtitle": "सबसे सटीक स्वास्थ्य मूल्यांकन खोजने के लिए नैदानिक जोखिम कारकों द्वारा डायग्नोस्टिक परीक्षण देखें।",
    "diag.list.habitTitle": "व्यापक आदत श्रेणियां",
    "diag.list.habitSubtitle": "जीवनशैली के पैटर्न और नियमित आदतों के आधार पर प्रासंगिक डायग्नोस्टिक जांच खोजें।",
    "diag.list.explore": "टेस्ट देखें",
    "page.spec.list.title": "हमारी विशेषज्ञता (Our Specialities)",
    "page.spec.list.subtitle": "सभी प्रमुख नैदानिक विभागों में विश्व स्तरीय चिकित्सा विशेषज्ञता।",
    "page.spec.list.badge": "उत्कृष्टता केंद्र",
    "page.spec.list.back": "विशेषज्ञता पर वापस जाएं",
    "page.spec.list.viewDetail": "विवरण देखें",
    "nav.findDoctor": "डॉक्टर खोजें",
    "nav.contact": "संपर्क करें",
    "nav.bookAppointment": "अभी बुक करें",
    "header.emergency": "Reception: 011-40793535, 8588831732",
    // About dropdown
    "nav.about.overview": "परिचय",
    "nav.about.corporate": "हमारी कॉर्पोरेट प्रोफाइल",
    "nav.about.director": "चेयरमैन का संदेश",
    "nav.about.vision": "दृष्टि और मिशन",
    "nav.about.management": "प्रबंधन टीम",
    "nav.about.services247": "24x7 सेवाएं",
    "nav.about.accreditation": "मान्यताएं",
    // Specialities
    "nav.spec.medicine": "आंतरिक चिकित्सा",
    "nav.spec.obst": "प्रसूति एवं स्त्री रोग",
    "nav.spec.endo": "एंडोक्राइनोलॉजी",
    "nav.spec.infectious": "संक्रामक रोग",
    "nav.spec.surgery": "सर्जरी",
    "nav.spec.ortho": "अस्थि रोग",
    "nav.spec.cardiology": "कार्डियोलॉजी",
    "nav.spec.neuro": "न्यूरोलॉजी",
    "nav.spec.paediatrics": "बाल रोग",
    "nav.spec.urology": "यूरोलॉजी",
    "nav.spec.gastro": "गैस्ट्रोएंटेरोलॉजी",
    "nav.spec.psychiatry": "मनोचिकित्सा (Psychiatry)",
    "nav.spec.dentistry": "दंत चिकित्सा (Dentistry)",
    "nav.spec.radiology": "रेडियोलॉजी",
    "nav.spec.pathology": "पैथोलॉजी",
    "nav.spec.ophthalmology": "नेत्र विज्ञान",
    "nav.spec.maxillofacial": "ओरल मैक्सिलोफेशियल सर्जरी",
    // COE dropdown
    "nav.coe.maternity": "मातृत्व केंद्र",
    "nav.coe.laparoscopic": "लेप्रोस्कोपिक एवं सामान्य सर्जरी",
    "nav.coe.pediatrics": "बाल चिकित्सा एवं नवजात विज्ञान",
    "nav.coe.interventional": "इंटरवेंशनल रेडियोलॉजी",
    "nav.coe.nephrology": "नेफ्रोलॉजी",
    "nav.coe.urology": "यूरोलॉजी एवं एंड्रोलॉजी",
    "nav.coe.ortho": "जोड़ प्रतिस्थापन केंद्र",
    "nav.coe.bariatric": "बेरिएट्रिक सर्जरी केंद्र",
    "nav.coe.cancer": "कैंसर देखभाल केंद्र",
    "nav.coe.emergency": "आपातकाल एवं ट्रॉमा",
    "nav.coe.icu": "क्रिटिकल केयर एवं आईसीयू",
    // Patient dropdown
    "nav.patient.rights": "मरीज़ के अधिकार",
    "nav.patient.feedback": "प्रतिक्रिया",
    "nav.patient.insurance": "बीमा सहायता",
    "nav.patient.visiting": "मुलाकात का समय",
    // Hero
    "hero.tagline": "प्रेम और देखभाल के माध्यम से स्वास्थ्य का लक्ष्य",
    "hero.subtitle":
      "2011 से क्लिनिकल उत्कृष्टता और करुणा के साथ सेवारत पूर्वी दिल्ली में एक मल्टी स्पेशलिटी अस्पताल।",
    "hero.cta.book": "अपॉइंटमेंट बुक करें",
    "hero.cta.specialities": "हमारी विशेषताएं",
    "hero.badge": "NABH मान्यता प्राप्त अस्पताल",
    // Stats
    "stats.years": "वर्षों की उत्कृष्टता",
    "stats.doctors": "विशेषज्ञ डॉक्टर",
    "stats.patients": "संतुष्ट मरीज़",
    "stats.specialities": "विशेषताएं",
    // Services
    "services.title": "हमारी विशेषताएं",
    "services.subtitle":
      "विशेषज्ञ डॉक्टर जो संपूर्ण देखभाल प्रदान करते हैं।",
    "services.viewmore": "सभी विशेषताएं देखें",
    // Spec descriptions
    "spec.medicine.desc": "वयस्क रोगों के निवारक देखभाल, निदान और उपचार के लिए हमारे विशेषज्ञों पर भरोसा करें।",
    "spec.obst.desc": "गर्भावस्था, प्रसव और सभी स्त्री रोग संबंधी स्थितियों में संपूर्ण मातृ देखभाल।",
    "spec.obst.t1": "मातृत्व और उच्च जोखिम वाली गर्भावस्था",
    "spec.obst.t2": "लेप्रोस्कोपिक स्त्री रोग सर्जरी",
    "spec.obst.t3": "बांझपन और आईवीएफ क्लिनिक",
    "spec.endo.desc": "मधुमेह, थायराइड और अन्य अंतःस्रावी तंत्र से संबंधित विकारों में विशेषज्ञ देखभाल।",
    "spec.endo.t1": "मधुमेह और थायराइड प्रबंधन",
    "spec.endo.t2": "मोटापा और वजन प्रबंधन",
    "spec.endo.t3": "हार्मोनल विकार",
    "spec.infectious.desc": "विभिन्न संक्रमणों और संचारी रोगों के लिए व्यापक निदान और उपचार।",
    "spec.infectious.t1": "बुखार और अज्ञात कारण",
    "spec.infectious.t2": "टीकाकरण",
    "spec.infectious.t3": "यात्रा चिकित्सा",
    "spec.surgery.desc": "हमारे मॉड्यूलर ऑपरेशन थिएटर में कैंसर सर्जरी से लेकर बेरिएट्रिक सर्जरी तक।",
    "spec.surgery.t1": "न्यूनतम पहुंच सर्जरी (Minimal Access)",
    "spec.surgery.t2": "बेरियाट्रिक और वजन कम करने की सर्जरी",
    "spec.surgery.t3": "ऑन्को-सर्जरी (कैंसर की सर्जरी)",
    "spec.ortho.desc": "हड्डी और जोड़ों की समस्याओं, फ्रैक्चर और गठिया के लिए विशेषज्ञ देखभाल।",
    "spec.ortho.t1": "घुटना और कूल्हा प्रत्यारोपण",
    "spec.ortho.t2": "आर्थ्रोस्कोपी और खेल चोटें",
    "spec.ortho.t3": "जटिल आघात और फ्रैक्चर देखभाल",
    "spec.cardiology.desc": "उन्नत हृदय देखभाल, आपातकालीन प्रतिक्रिया और सर्जरी के बाद पुनर्वास।",
    "spec.cardiology.t1": "कोरोनरी एंजियोग्राफी",
    "spec.cardiology.t2": "इकोकार्डियोग्राफी (ईसीजी, टीएमटी)",
    "spec.cardiology.t3": "हार्ट फेलियर क्लिनिक",
    "spec.neuro.desc": "जटिल न्यूरोलॉजिकल और मस्तिष्क स्थितियों का निदान और प्रबंधन।",
    "spec.neuro.t1": "स्ट्रोक और लकवा प्रबंधन",
    "spec.neuro.t2": "सिरदर्द और माइग्रेन थेरेपी",
    "spec.neuro.t3": "मिर्गी क्लीनिक",
    "spec.paediatrics.desc": "चौबीसों घंटे बाल चिकित्सा आपातकाल, एनआईसीयू और बाल देखभाल।",
    "spec.paediatrics.t1": "नवजात गहन चिकित्सा (NICU)",
    "spec.paediatrics.t2": "बाल चिकित्सा टीकाकरण",
    "spec.paediatrics.t3": "बाल विकास क्लीनिक",
    "spec.urology.desc": "मूत्र पथ के रोगों और पुरुष प्रजनन प्रणाली की स्थितियों का उपचार।",
    "spec.urology.t1": "किडनी स्टोन लेजर रिमूवल",
    "spec.urology.t2": "प्रोस्टेट सर्जरी (TURP)",
    "spec.urology.t3": "यूरो-ऑन्कोलॉजी",
    // Why choose us
    "why.title": "करुणा हॉस्पिटल क्यों चुनें?",
    "why.clinical.title": "नैदानिक उत्कृष्टता",
    "why.clinical.desc":
      "विशेषज्ञताओं में 200 से अधिक वर्षों का सामूहिक नैदानिक अनुभव।",
    "why.lab.title": "अत्याधुनिक प्रयोगशाला",
    "why.lab.desc": "Oncquest Laboratories के साथ संपूर्ण डायग्नोस्टिक सेवाएं।",
    "why.emergency.title": "24/7 आपातकालीन सेवाएं",
    "why.emergency.desc":
      "त्वरित एम्बुलेंस सेवाओं के साथ आघात और दुर्घटना में तुरंत प्रतिक्रिया।",
    "why.pharmacy.title": "इन-हाउस फार्मेसी",
    "why.pharmacy.desc": "उपचार के हर चरण में गुणवत्तापूर्ण दवाएं उपलब्ध।",
    // Director
    "director.title": "निदेशक का संदेश",
    "director.name": "डॉ. (निदेशक)",
    "director.quote":
      '"करुणा" हमारे स्पष्ट संचार में झलकती है, जो मरीज़ों को घर जैसा महसूस कराती है।',
    "director.readmore": "और पढ़ें",
    // CTA
    "cta.title": "आज ही बेहतर स्वास्थ्य की ओर अपनी यात्रा शुरू करें",
    "cta.subtitle":
      "हमारी विशेषज्ञ डॉक्टरों की टीम आपको सर्वोत्तम देखभाल प्रदान करने के लिए तैयार है।",
    "cta.button": "अपॉइंटमेंट बुक करें",
    // Footer
    // Inner Pages Common
    "page.back_home": "होम पर वापस जाएं",
    "page.error.title": "जानकारी नहीं मिली",
    // COE
    "page.coe.notfound": "आप जिस उत्कृष्टता केंद्र की तलाश कर रहे हैं वह मौजूद नहीं है या हटा दिया गया है।",
    "page.coe.badge": "उत्कृष्टता केंद्र",
    "page.coe.welcome": "में आपका स्वागत है",
    "page.coe.desc": "हम विश्व स्तरीय देखभाल प्रदान करने के लिए समर्पित हैं। हमारी विशेषज्ञ टीम सर्वोत्तम संभव चिकित्सा परिणाम सुनिश्चित करने के लिए नवीनतम साक्ष्य-आधारित प्रोटोकॉल और अत्याधुनिक सुविधाओं का उपयोग करती है। करुणा अस्पताल में, हमारा ध्यान हमेशा रोगी-केंद्रित देखभाल पर होता है।",
    "page.coe.expert": "विशेषज्ञ देखभाल",
    "page.coe.expert.desc": "अपने-अपने क्षेत्रों में वर्षों के नैदानिक ​​अनुभव वाले उच्च योग्य विशेषज्ञ।",
    "page.coe.advanced": "उन्नत सुविधाएं",
    "page.coe.advanced.desc": "आपके स्वास्थ्य को प्राथमिकता देने वाले अत्याधुनिक चिकित्सा उपकरण और आधुनिक बुनियादी ढांचे।",
    "page.cta.healing": "आज ही अपनी स्वास्थ्य लाभ यात्रा शुरू करें",
    "page.cta.healing.desc": "हमारे उच्च अनुभवी विशेषज्ञों के साथ परामर्श बुक करें।",
    // Speciality
    "page.spec.notfound": "आप जिस स्पेशलिटी विभाग की तलाश कर रहे हैं वह मौजूद नहीं है या हटा दिया गया है।",
    "page.spec.badge": "स्पेशलिटी विभाग",
    "page.spec.welcome": "में आपका स्वागत है",
    "page.spec.desc": "हमारी विशेषज्ञ मेडिकल टीम संबंधित स्थितियों के निदान और उपचार के लिए गहराई से प्रतिबद्ध है। आधुनिक चिकित्सा तकनीक से लैस और अग्रणी साक्ष्य-आधारित प्रथाओं का पालन करते हुए, हम आपके स्वास्थ्य और पुनर्प्राप्ति यात्रा के लिए समर्पित एक व्यापक दृष्टिकोण प्रदान करते हैं।",
    "page.spec.expert": "महारत प्राप्त विशेषज्ञ",
    "page.spec.expert.desc": "हमारी टीम में जटिल स्थितियों के निदान में विशेषज्ञता रखने वाले कुछ प्रमुख डॉक्टर शामिल हैं।",
    "page.spec.patient": "रोगी सर्वप्रथम देखभाल",
    "page.spec.patient.desc": "आराम, पारदर्शिता और बेहतर परिणामों पर ध्यान केंद्रित करने वाला एक अत्यधिक व्यक्तिगत देखभाल मॉडल।",
    "page.spec.treatments": "मुख्य उपचार और सेवाएं",
    "page.cta.consult": "परामर्श निर्धारित करें",
    "page.cta.consult.desc": "अपने स्वास्थ्य संबंधी चिंताओं के बारे में आज ही हमारे विशेषज्ञ सलाहकारों से बात करें।",
    // Patient
    "page.patient.badge": "रोगी की जानकारी",
    "page.patient.rights.desc": "प्रत्येक रोगी को विचारशील और सम्मानजनक देखभाल का अधिकार है। करुणा अस्पताल में, हम यह सुनिश्चित करने के लिए समर्पित हैं कि आप अपनी स्वास्थ्य देखभाल यात्रा के दौरान सूचित, सुरक्षित और सशक्त महसूस करें। हमारी नीतियां व्यक्तिगत गरिमा का सम्मान करने और अत्यंत गोपनीयता बनाए रखने के लिए डिज़ाइन की गई हैं।",
    "page.patient.feedback.desc": "आपकी प्रतिक्रिया हमारे लिए अमूल्य है। हम अपनी सेवाओं और रोगी अनुभवों को बेहतर बनाने के लिए निरंतर प्रयास करते हैं। चाहे आपके पास हमारे कर्मचारियों के लिए कोई प्रशंसा हो या हम बेहतर कैसे कर सकते हैं इसके लिए कोई सुझाव हो, हम आपसे सुनना चाहते हैं।",
    "page.patient.insurance.desc": "हम समझते हैं कि स्वास्थ्य देखभाल के वित्तपोषण को नेविगेट करना चुनौतीपूर्ण हो सकता है। करुणा अस्पताल प्रमुख स्वास्थ्य बीमा प्रदाताओं और टीपीए के साथ कैशलेस अस्पताल में भर्ती सुविधाएं प्रदान करने के लिए पैनल में है। हमारा समर्पित बीमा डेस्क पूर्व-प्राधिकरण और दावों में आपकी सहायता के लिए यहां है।",
    "page.patient.visiting.desc": "यह सुनिश्चित करने के लिए कि हमारे रोगियों को अपने प्रियजनों के साथ जुड़े रहते हुए आवश्यक आराम मिले, हमने विशिष्ट मुलाकात के घंटे स्थापित किए हैं। सामान्य वार्डों में, दिन में दो बार जाने की अनुमति है। आईसीयू में, गंभीर रोगियों के लिए एक बाँझ और शांत वातावरण सुनिश्चित करने के लिए जाना प्रतिबंधित है।",
    // About
    "page.about.title": "हम कौन हैं",
    "page.about.subtitle": "स्थानीय समुदाय के लिए स्वास्थ्य सेवा में उत्कृष्टता और सहानुभूति।",
    "page.about.heroSubtitle": "क्लिनिकल उत्कृष्टता और दयालु देखभाल के लिए समर्पित पूर्वी दिल्ली का एक प्रमुख मल्टी-स्पेशियलिटी अस्पताल।",
    "page.about.overview": "करुणा अस्पताल के बारे में",
    "page.about.p1": "2011 में स्थापित, करुणा अस्पताल की स्थापना एक विलक्षण उद्देश्य के साथ की गई थी: उन लोगों की स्वास्थ्य देखभाल आवश्यकताओं में अंतर को दूर करना जिन्हें वास्तव में इसकी आवश्यकता है। इन वर्षों में, हम पूर्वी दिल्ली में एक विश्वसनीय मल्टी-स्पेशियलिटी हेल्थकेयर सुविधा के रूप में विकसित हुए हैं, जो अत्यधिक सहानुभूतिपूर्ण दृष्टिकोण के साथ नैदानिक ​​उत्कृष्टता के संयोजन के लिए जाना जाता है।",
    "page.about.p2": "अनुभवी डॉक्टरों और चिकित्सा पेशेवरों की हमारी समर्पित टीम उच्च गुणवत्ता वाली, किफायती स्वास्थ्य सेवा प्रदान करने के लिए उन्नत तकनीक का लाभ उठाती है।",
    "page.about.corporate.title": "हमारी कॉर्पोरेट प्रोफाइल",
    "page.about.chairman.title": "चेयरमैन का संदेश",
    "page.about.management.title": "प्रबंधन टीम",
    "page.about.services247.title": "24x7 सेवाएं",
    "page.about.vision.title": "हमारा दृष्टिकोण",
    "page.about.vision.desc": "करुणा अस्पताल अपने सभी प्रयासों में उत्कृष्टता प्राप्त करना चाहता है, सभी वर्गों के लोगों को सस्ती कीमतों पर अत्याधुनिक चिकित्सा सेवाएं प्रदान करने की आकांक्षा रखता है, लंबे समय तक चलने वाले डॉक्टर-मरीज संबंध स्थापित करता है, और एक ऐसे वातावरण का पोषण करता है जहां स्वास्थ्य सेवा प्रदाता और कर्मचारी सीख सकें और पनप सकें।",
    "page.about.mission.title": "हमारा लक्ष्य",
    "page.about.mission.desc": "करुणा का अर्थ है सहानुभूति, हमारा नाम समग्र रूप से हमारे मिशन का प्रतीक है। करुणा और सम्मान के साथ सभी को उत्कृष्ट स्वास्थ्य सुविधाएं प्रदान करना, और प्यार और देखभाल के साथ निवारक शिक्षा और सेवाओं के माध्यम से समुदाय में कल्याण और अच्छे स्वास्थ्य को बढ़ावा देना।",
    "page.about.values.title": "गुणवत्ता मूल्य और पहल",
    "page.about.values.1": "मरीजों और उनके परिवारों को असाधारण देखभाल प्रदान करना।",
    "page.about.values.2": "हर मरीज और स्टाफ सदस्य की गरिमा और व्यक्तित्व को स्वीकार करना।",
    "page.about.values.3": "मरीज की गोपनीयता और गोपनीयता का सम्मान करना।",
    "page.about.values.4": "मरीजों और कर्मचारियों के साथ खुले और प्रभावी ढंग से संवाद करना।",
    "page.about.values.5": "ईमानदारी और नैतिक आचरण के उच्चतम मानकों को बनाए रखना।",
    "page.about.values.6": "सभी स्तरों पर टीम वर्क और जवाबदेही को बढ़ावा देना।",
    "page.about.values.7": "निरंतर मूल्यांकन और प्रदर्शन में सुधार को बढ़ावा देना।",
    "page.about.values.8": "वित्तीय भलाई और जिम्मेदारी सुनिश्चित करने के लिए कुशल और विवेकपूर्ण प्रबंधन प्रथाओं का निर्माण करना।",
    "page.about.awards.title": "पुरस्कार और मान्यताएं",
    "page.about.awards.desc": "हमें देश में प्रमुख स्वास्थ्य और गुणवत्ता नियामकों द्वारा मान्यता प्राप्त होने पर गर्व है। यह सुनिश्चित करता है कि हर परीक्षण, प्रक्रिया और सर्जरी वैश्विक सुरक्षा और गुणवत्ता मानकों को पूरा करती है।",
    // Career
    "page.career.title": "हमारी टीम में शामिल हों",
    "page.career.subtitle": "सहानुभूति और नैदानिक ​​उत्कृष्टता पर ध्यान केंद्रित करते हुए एक पुरस्कृत करियर बनाएं।",
    "page.career.why": "हमारे साथ काम क्यों करें?",
    "page.career.why.desc": "करुणा अस्पताल में, हमारे कर्मचारी हमारी सबसे बड़ी संपत्ति हैं। हम एक सहयोगी, समावेशी और आधुनिक कार्य वातावरण को बढ़ावा देते हैं जहां उच्च प्रशिक्षित पेशेवरों को पनपने, नया करने और हमारे रोगियों के जीवन में सक्रिय बदलाव लाने के लिए प्रोत्साहित किया जाता है।",
    "page.career.growth": "विकास के अवसर",
    "page.career.growth.desc": "हम कठोर प्रशिक्षण और सलाह के माध्यम से निरंतर सीखने और व्यावसायिक विकास को प्राथमिकता देते हैं।",
    "page.career.collab": "सहयोगी संस्कृति",
    "page.career.collab.desc": "बहुआयामी टीमों में काम करें जहां समग्र रोगी की देखभाल सुनिश्चित करते हुए आपके इनपुट को महत्व दिया जाता है।",
    "page.career.openings": "वर्तमान रिक्तियां",
    "page.career.apply": "अभी आवेदन करें",
    "page.career.cantfind": "मेल खाने वाली भूमिका नहीं मिल रही है?",
    "page.career.sendresume": "हमारे मानव संसाधन विभाग को अपना बायोडाटा भेजें और उपयुक्त पद खुलने पर हम आपसे संपर्क करेंगे।",
    "page.career.contacthr": "मानव संसाधन विभाग से संपर्क करें →",
    // Contact
    "page.contact.title": "संपर्क करें",
    "page.contact.subtitle": "अपॉइंटमेंट, पूछताछ या फीडबैक के लिए हमसे संपर्क करें।",
    "page.contact.info": "प्रासंगिक जानकारी",
    "page.contact.address.label": "पता",
    "page.contact.phone.label": "फ़ोन",
    "page.contact.email.label": "ईमेल",
    "page.contact.hero.title": "संपर्क करें",
    "page.contact.hero.subtitle": "अपॉइंटमेंट, आपात स्थिति या सामान्य पूछताछ के लिए संपर्क करें। हमारी टीम 24/7 आपकी सहायता के लिए यहाँ है।",
    "page.contact.getInTouch": "संपर्क में रहें",
    "page.contact.getInTouch.desc": "हम 24/7 आपकी सहायता के लिए उपलब्ध हैं। अपॉइंटमेंट, आपात स्थिति या सामान्य पूछताछ के लिए संपर्क करें।",
    "page.contact.card.location": "हमारा पता",
    "page.contact.card.address": "D-62, पॉकेट E, दिलशाद कॉलोनी, नई दिल्ली, दिल्ली, 110095",
    "page.contact.card.call": "हमें कॉल करें",
    "page.contact.card.email": "ईमेल",
    "page.contact.card.emergency": "आपातकालीन",
    "page.contact.card.emergency.desc": "24/7 उपलब्ध — किसी भी समय कॉल करें",
    "page.contact.form.title": "हमें संदेश भेजें",
    "page.contact.form.subtitle": "नीचे दिया गया फॉर्म भरें या हमें सीधे व्हाट्सएप पर संदेश भेजें। हमारी टीम जल्द ही जवाब देगी।",
    "page.contact.form.name.label": "पूरा नाम",
    "page.contact.form.email.label": "ईमेल पता",
    "page.contact.form.phone.label": "फ़ोन नंबर",
    "page.contact.form.subject.label": "विषय",
    "page.contact.form.message.label": "आपका संदेश",
    "page.contact.form.privacy": "आपकी जानकारी सुरक्षित है। हम इसका उपयोग केवल आपकी पूछताछ का जवाब देने के लिए करते हैं।",
    "page.contact.form.privacy.link": "गोपनीयता नीति",
    "page.contact.form.sending": "भेजा जा रहा है...",
    "page.contact.form.sent": "संदेश भेजा गया!",
    "page.contact.form.send.btn": "फॉर्म के माध्यम से संदेश भेजें",
    "page.contact.form.or": "अथवा",
    "page.contact.form.whatsapp": "व्हाट्सएप पर चैट करें",
    "page.contact.form.emergency.notice": "चिकित्सा आपात स्थिति के लिए, तुरंत हमारे रिसेप्शन पर कॉल करें।",
    "page.contact.form.subject.appointment": "अपॉइंटमेंट बुक करें",
    "page.contact.form.subject.inquiry": "सामान्य पूछताछ",
    "page.contact.form.subject.feedback": "प्रतिक्रिया",
    "page.contact.form.subject.emergency": "आपातकालीन सहायता",
    "page.contact.form.subject.other": "अन्य",
    // News
    "page.news.title": "नवीनतम अद्यतन",
    "page.news.readfull": "पूरा लेख पढ़ें",
    "footer.quicklinks": "त्वरित लिंक",
    "footer.contact": "संपर्क करें",
    "footer.rights": "© 2024 करुणा हॉस्पिटल। सर्वाधिकार सुरक्षित।",
    "footer.nabh": "NABH मान्यता प्राप्त",
    "footer.tagline": "दयालु देखभाल, विश्व स्तरीय विशेषज्ञता। करुणा अस्पताल उच्च गुणवत्ता वाली स्वास्थ्य देखभाल और चिकित्सा उत्कृष्टता प्रदान करने के लिए समर्पित है।",
    "footer.address": "D-62, पॉकेट E, दिलशाद कॉलोनी, नई दिल्ली, दिल्ली, 110095",
    "home.about.badge": "हमारे बारे में",
    "home.about.welcome": "स्वागत है",
    "home.about.p1.title": "2011 में स्थापित, करुणा अस्पताल दिल्ली में एक प्रमुख मल्टी-स्पेशियलिटी स्वास्थ्य सुविधा है। हम व्यापक, विश्व स्तरीय चिकित्सा सेवाएं प्रदान करने के लिए प्रतिबद्ध हैं।",
    "home.about.p2.desc": "सहानुभूति हमारे लोकाचार के मूल में है। अनुभवी डॉक्टरों और दयालु कर्मचारियों की हमारी टीम अत्याधुनिक बुनियादी ढांचे और सुलभ स्वास्थ्य पैकेजों की मदद से व्यक्तिगत देखभाल प्रदान करने के लिए अथक प्रयास करती है।",
    "home.about.discover": "अधिक जानें",
    "home.infra.title": "बुनियादी ढांचा और तकनीक",
    "home.infra.subtitle": "रोगी के आराम, सुरक्षा और उन्नत नैदानिक देखभाल के लिए डिज़ाइन की गई अत्याधुनिक सुविधाएं।",
    "home.infra.facility.title": "हमारी सुविधा",
    "home.infra.facility.desc": "पूर्वी दिल्ली में एक बहु-विशेषज्ञता स्वास्थ्य सेवा मील का पत्थर, जो 2011 से विश्व स्तरीय चिकित्सा सेवाएं प्रदान करने के लिए समर्पित है।",
    "home.infra.lobby.title": "प्रीमियम लॉबी",
    "home.infra.lobby.desc": "आधुनिक सुविधाओं के साथ रोगी के अनुकूल वातावरण।",
    "home.infra.care.title": "दयालु देखभाल",
    "home.infra.care.desc": "व्यक्तिगत ध्यान देने वाले विशेषज्ञ डॉक्टर।",
    "home.infra.ot.title": "मॉड्यूलर ओटी",
    "home.infra.ot.desc": "अत्याधुनिक सर्जिकल और डायग्नोस्टिक तकनीक से लैस।",
    "home.director.p1": "जैसा कि अस्पताल के नाम से पता चलता है, करुणा अस्पताल उन लोगों की स्वास्थ्य देखभाल आवश्यकताओं में अंतर को दूर करने के लिए स्थापित किया गया था जिन्हें वास्तव में इसकी आवश्यकता है।",
    "home.director.cite": "निदेशक, करुणा अस्पताल",
    "page.about.chairman.label": "चेयरमैन का संदेश",
    "page.about.director.title": "निदेशक का संदेश",
    "page.about.chairman.p1": "जैसा कि अस्पताल के नाम से पता चलता है, करुणा अस्पताल उन लोगों की स्वास्थ्य देखभाल आवश्यकताओं में अंतर को दूर करने के लिए स्थापित किया गया था जिन्हें वास्तव में इसकी आवश्यकता है। हमारी प्रक्रियाएं, डॉक्टरों की भर्ती, उपचार और अत्याधुनिक बुनियादी ढांचे सभी को इस अंतर को पाटने के लिए डिज़ाइन किया गया है।",
    "page.about.chairman.p2": "चिकित्सा अभ्यास के मेरे 35 वर्षों में, मैंने चिकित्सा ज्ञान और करुणा के संयोजन से होने वाले चमत्कारों को देखा है।",
    "page.about.chairman.p3": "“करुणा” हमारे स्पष्ट संचार में झलकती है, जो मरीजों को घर जैसा महसूस कराती है, और जिस समझ के साथ हम उपचार करते हैं। यही हम अपने कर्मचारियों के व्यवहार, कार्य संस्कृति और पेशेवरता की धारणा में आत्मसात करने की कोशिश करते हैं, जबकि हजारों मरीजों को चौबीसों घंटे सेवाएं प्रदान करते हैं। हमारे मरीजों का विश्वास हमें आगे बढ़ने और सभी के लिए स्वास्थ्य सेवा सुनिश्चित करने के लिए सशक्त बनाता है।",
    "page.about.chairman.name": "डॉ. राजीव गुप्ता",
    "page.about.chairman.desig": "चेयरमैन एवं निदेशक",
    "page.about.mgmt.title": "निदेशक मंडल",
    "page.about.mgmt.desc": "करुणा अस्पताल के विकास और उत्कृष्टता में योगदान देने वाले समर्पित पेशेवर।",
    "page.about.service.emergency": "आपातकालीन और ट्रॉमा",
    "page.about.service.emergency.desc": "विशेषज्ञ ट्रॉमा टीमों के साथ चौबीसों घंटे आपातकालीन प्रतिक्रिया।",
    "page.about.service.lab": "डायग्नोस्टिक लैब",
    "page.about.service.lab.desc": "24/7 हाई-एंड डायग्नोस्टिक परीक्षण और इमेजिंग सेवाएं।",
    "page.about.service.pharmacy": "फार्मेसी",
    "page.about.service.pharmacy.desc": "गुणवत्तापूर्ण स्वास्थ्य देखभाल दवाओं और आपूर्ति तक निरंतर पहुंच।",
    "page.about.service.ambulance": "एम्बुलेंस",
    "page.about.service.ambulance.desc": "तत्काल एम्बुलेंस पिक-अप और परिवहन 24/7 उपलब्ध।",
    "page.about.values.long": "करुणा अस्पताल में, उत्कृष्टता हमारे हर काम को संचालित करती है। हम सभी समुदायों को अत्याधुनिक, सस्ती स्वास्थ्य सेवा प्रदान करते हैं, स्थायी डॉक्टर-रोगी भागीदारी बनाते हैं, और एक सहायक कार्यस्थल को पोषित करते हैं जहां हमारे कर्मचारी बढ़ सकें और उत्कृष्टता प्राप्त कर सकें। क्षेत्र की बेहतरीन स्वास्थ्य देखभाल टीम द्वारा समर्थित, हम ईमानदारी और करुणा के साथ असाधारण देखभाल प्रदान करते हैं।",
    "page.about.mission.heading": "परिष्कृत मिशन वक्तव्य",
    "page.about.mission.long": "करुणा अस्पताल हम जो कुछ भी करते हैं उसमें उत्कृष्टता के लिए प्रतिबद्ध है। हम किफायती कीमतों पर समाज के हर वर्ग को अत्याधुनिक चिकित्सा देखभाल प्रदान करने, स्थायी डॉक्टर-रोगी संबंध बनाने और एक ऐसा वातावरण विकसित करने का प्रयास करते हैं जहाँ स्वास्थ्य देखभाल पेशेवर और कर्मचारी लगातार सीख सकें और पनप सकें। एक असाधारण टीम द्वारा संचालित, हम दयालु, उच्च गुणवत्ता वाली स्वास्थ्य सेवा में मानक स्थापित करने के लिए समर्पित हैं।",
    "page.diag.hero.badge": "अत्याधुनिक डायग्नोस्टिक्स",
    "page.diag.hero.title": "सटीक निदान, व्यक्तिगत देखभाल।",
    "page.diag.hero.subtitle": "करुणा अस्पताल एंड-टू-एंड नैदानिक ​​आकलन प्रदान करने के लिए प्रमुख प्रयोगशालाओं के साथ साझेदारी करता है। नीचे अपनी स्वास्थ्य स्क्रीनिंग के लिए सही रास्ता चुनें।",
    "page.diag.hero.accuracy": "99.9% सटीकता",
    "page.diag.hero.processing": "24/7 प्रसंस्करण",
    "page.diag.hero.reports": "डिजिटल रिपोर्ट",
    "page.diag.cat.habit.title": "आदत के अनुसार ब्राउज़ करें",
    "page.diag.cat.habit.desc": "धूम्रपान, तनाव और नियमित पैटर्न के लिए जीवनशैली-आधारित स्क्रीनिंग।",
    "page.diag.cat.habit.stats": "20+ आदत जाँच",
    "page.diag.cat.risk.title": "जोखिम के अनुसार ब्राउज़ करें",
    "page.diag.cat.risk.desc": "मधुमेह या हृदय रोग जैसे विशिष्ट नैदानिक ​​जोखिमों के लिए लक्षित निदान।",
    "page.diag.cat.risk.stats": "30+ जोखिम प्रोफाइल",
    "page.diag.cat.package.title": "स्वास्थ्य पैकेज",
    "page.diag.cat.package.desc": "सभी आयु समूहों और आवश्यकताओं के लिए क्यूरेट किया गया व्यापक फुल-बॉडी चेकअप।",
    "page.diag.cat.package.stats": "15+ बंडल योजनाएं",
    "page.diag.trust.title": "हमारा नैदानिक ​​आकलन क्यों अलग है।",
    "page.diag.trust.global.title": "वैश्विक मानक",
    "page.diag.trust.global.desc": "हमारे नैदानिक ​​नैदानिक ​​प्रोटोकॉल कुल सुरक्षा के लिए NABH और ISO बेंचमार्क के साथ संरेखित हैं।",
    "page.diag.trust.expert.title": "विशेषज्ञ व्याख्या",
    "page.diag.trust.expert.desc": "रिलीज़ होने से पहले हर रिपोर्ट की समीक्षा विशेष रोगविज्ञानी और एमडी चिकित्सकों द्वारा की जाती है।",
    "page.diag.trust.stat.tat": "नियमित के लिए TAT",
    "page.diag.trust.stat.available": "परीक्षण उपलब्ध",
    "page.diag.trust.stat.lab": "लैब उपलब्धता",
    "page.diag.trust.stat.patient": "रोगी पहले",
    "page.diag.help.title": "सहायता चाहिए?",
    "page.diag.help.subtitle": "सही परीक्षण चुनने में सहायता चाहिए? हमारी विशेषज्ञ नैदानिक ​​टीम मार्गदर्शन के लिए उपलब्ध है।",
    "page.diag.help.cta": "एक विशेषज्ञ से बात करें",
    "page.doctors.badge": "अपना डॉक्टर खोजें",
    "page.doctors.title": "हमारी विशेषज्ञ चिकित्सा टीम",
    "page.doctors.hero.p1": "2011 में स्थापित, करुणा अस्पताल ओपीडी और आईपीडी दोनों सेवाओं में अपनी विशेषज्ञता के लिए जाना जाता है। सहानुभूति हमारी सेवाओं के मूल में है जो हमारे विशेषज्ञ डॉक्टरों के दयालु उपचार और सुलभ लागत संरचना में झलकती है।",
    "page.doctors.hero.p2": "विभिन्न विशिष्टताओं में विशेषज्ञता रखने वाले अनुभवी डॉक्टर करुणा अस्पताल से जुड़े हुए हैं। इससे हमें अपने मरीजों की समस्याओं को बेहतर ढंग से समझने और पूर्ण देखभाल प्रदान करने में मदद मिलती है।",
    "page.doctors.card.experience": "वर्षों का अनुभव",
    "page.doctors.card.viewProfile": "प्रोफ़ाइल देखें",
    "page.doctors.card.location": "दिलशाद कॉलोनी, नई दिल्ली",
    "page.news.badge": "नवीनतम अपडेट",
    "page.news.hero.subtitle": "करुणा अस्पताल के नवीनतम नैदानिक ​​सफलताओं, सामुदायिक सेवा पहलों और अस्पताल की घोषणाओं के साथ अपडेट रहें।",
    "page.news.featured": "विशेष रुप से प्रदर्शित",
    "page.news.milestone": "उपलब्धि",
    "page.news.community": "समुदाय",
    "page.news.expansion": "विस्तार",
    "page.news.innovation": "नवाचार",
    "page.news.award": "पुरस्कार",
    "page.news.hospital": "अस्पताल समाचार",
    "page.news.readTime": "मिनट का पाठ",
    "page.doctor.back": "डॉक्टरों पर वापस जाएं",
    "page.doctor.verified": "सत्यापित विशेषज्ञ",
    "page.doctor.patients": "मरीज",
    "page.doctor.rating": "रेटिंग",
    "page.doctor.tagline": "करुणा अस्पताल, दिलशाद कॉलोनी, नई दिल्ली में वरिष्ठ विशेषज्ञ — दयालु, प्रमाण-आधारित चिकित्सा देखभाल प्रदान करने के लिए समर्पित।",
    "page.doctor.about": "के बारे में",
    "page.doctor.book": "परामर्श बुक करें",
    "page.doctor.availability": "उपलब्धता",
    "page.doctor.mon_sat": "सोम – शनि, सुबह 9 बजे – शाम 6 बजे",
    "page.doctor.location": "करुणा अस्पताल, दिलशाद कॉलोनी, नई दिल्ली",
    "page.doctor.why": "करुणा अस्पताल ही क्यों?",
    "page.doctor.needexpert": "विशेषज्ञ चिकित्सा सलाह चाहिए?",
    "page.doctor.schedule": "व्यक्तिगत, विश्व स्तरीय देखभाल के लिए आज ही अपना अपॉइंटमेंट शेड्यूल करें।",
    "page.doctor.years": "वर्ष",
    "page.doctor.education": "शिक्षा",
    "page.doctor.interests": "रुचि के क्षेत्र",
    "page.doctor.associations": "अस्पताल संघ",
    "page.career.badge": "हमारे मिशन में शामिल हों",
    "page.career.joinus": "हमारे साथ काम करें",
    "page.career.quote": "एक ऐसी जगह जहाँ करुणा अस्पताल में चिकित्सा उत्कृष्टता और दयालु देखभाल का मिलन होता है।",
    "page.career.progrowth": "व्यावसायिक विकास",
    "page.career.progrowth.desc": "करुणा अस्पताल में आपके चिकित्सा करियर को आगे बढ़ाने के लिए निरंतर सीखने और विकास के अवसर।",
    "page.career.collab.env": "सहयोगात्मक वातावरण",
    "page.career.collab.env.desc": "एक सहायक, टीम-उन्मुख संस्कृति में सर्वश्रेष्ठ चिकित्सा पेशेवरों के साथ काम करें।",
    "page.career.excellence": "उत्कृष्टता और मान्यता",
    "page.career.excellence.desc": "हम उत्कृष्ट रोगी देखभाल, समर्पण और नैदानिक ​​उत्कृष्टता को महत्व देते हैं और पुरस्कृत करते हैं।",
    "page.career.tech": "उन्नत तकनीक",
    "page.career.tech.desc": "अत्याधुनिक चिकित्सा उपकरणों और अभिनव स्वास्थ्य देखभाल समाधानों तक पहुंच।",
    "page.career.openings.p": "सर्वोत्तम स्वास्थ्य सेवाएं प्रदान करने के लिए समर्पित विशेषज्ञों और सहायक कर्मचारियों की हमारी टीम में शामिल हों।",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
